fix CI build

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -21,3 +21,10 @@ parts:
       - libssl-dev
       - rustc
       - cargo
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
