update charmcraft.yaml to be similar to that of the k8s one

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -13,13 +13,15 @@ bases:
 parts:
   charm:
     charm-strict-dependencies: true
-    override-pull: |
+    override-build: |
+      rustup default stable
+      # Convert subset of poetry.lock to requirements.txt
+      curl -sSL https://install.python-poetry.org | python3 -
+      /root/.local/bin/poetry self add poetry-plugin-export
+      /root/.local/bin/poetry export --only main,charm-libs --output requirements.txt
       craftctl default
-      if [[ ! -f requirements.txt ]]
-      then
-          echo 'ERROR: Use "tox run -e build" instead of calling "charmcraft pack" directly' >&2
-          exit 1
-      fi
+    build-snaps:
+      - rustup
     build-packages:
       - libffi-dev
       - libssl-dev
@@ -29,3 +31,10 @@ parts:
     prime:
       - charm_version
       - workload_version
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build-dev" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
